from tkinter import *
root=Tk()
root.title("Calculator")
#Event calling
def clicked(event):
    global scval
    value=event.widget.cget("text")    
    if(value=="C"):
        scval.set("")
        screen.update()
    elif(value=="="):
        value=eval(screen.get())
        scval.set(value)
        screen.update()
    else:
        scval.set(scval.get()+value)
        screen.update()
def dark():
    root.destroy()   
scval=StringVar()
scval.set("")
screen=Entry(root,textvariable=scval,font="lucida 40 bold",borderwidth=10)
screen.pack()
root.geometry("425x560")
root.maxsize(425,560)
f1=Frame(root,bg="black")
btn=Button(f1,text="7",font="normal 35 italic")
btn.pack(padx=2,pady=10)
btn.bind('<Button-1>',clicked)
btn.bind('<Key>',clicked)
btn=Button(f1,text="4",font="normal 35 italic")
btn.pack(padx=2,pady=10)
btn.bind('<Button-1>',clicked)
btn=Button(f1,text="1",font="normal 35 italic")
btn.pack(padx=2,pady=10)
btn.bind('<Button-1>',clicked)
btn=Button(f1,text="00",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind('<Button-1>',clicked)
f1.pack(side=LEFT)

f1=Frame(root,bg="black")
btn=Button(f1,text="8",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind('<Button-1>',clicked)
btn=Button(f1,text="5",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind('<Button-1>',clicked)
btn=Button(f1,text="2",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind('<Button-1>',clicked)
btn=Button(f1,text=".",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind('<Button-1>',clicked)
f1.pack(side=LEFT)


f1=Frame(root,bg="black")
btn=Button(f1,text="9",font="normal 35 italic")
btn.pack(padx=10,pady=10)
btn.bind('<Button-1>',clicked)
btn=Button(f1,text="6",font="normal 35 italic")
btn.pack(padx=10,pady=10)
btn.bind('<Button-1>',clicked)
btn=Button(f1,text="3",font="normal 35 italic")
btn.pack(padx=10,pady=10)
btn.bind('<Button-1>',clicked)
btn=Button(f1,text="0",font="normal 35 italic")
btn.pack(padx=10,pady=10)
btn.bind('<Button-1>',clicked)
f1.pack(side=LEFT)

f1=Frame(root,bg="black")
btn=Button(f1,text="/",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind("<Button-1>",clicked)
btn=Button(f1,text="*",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind("<Button-1>",clicked)
btn=Button(f1,text="+",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind("<Button-1>",clicked)
btn=Button(f1,text="D",font="normal 35 italic",command=dark)
btn.pack(padx=5,pady=10)
f1.pack(side=LEFT)

f1=Frame(root,bg="black")
btn=Button(f1,text="C",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind("<Button-1>",clicked)
btn=Button(f1,text="%",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind("<Button-1>",clicked)
btn=Button(f1,text="-",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind("<Button-1>",clicked)
btn=Button(f1,text="=",font="normal 35 italic")
btn.pack(padx=5,pady=10)
btn.bind("<Button-1>",clicked)

f1.pack(side=LEFT)

root.mainloop()
